//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rezercontrols.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient_TABLE()
        {
            this.appointment_table = new HashSet<appointment_table>();
        }
    
        public int p_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string email_id { get; set; }
        public string pswrd { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> mobile_no { get; set; }
        public string p_address { get; set; }
        public string hobbies { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string profileimg { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment_table> appointment_table { get; set; }
        public virtual state_table State_Table { get; set; }
        public virtual city_table City_Table { get; set; }
    }
}
