//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM_crud.edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_email { get; set; }
        public string gender { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<int> mobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string hobbies { get; set; }
    }
}
