//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM_crud.edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_detail
    {
        public int std_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
