//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_TABLE
    {
        public int admin_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string email_id { get; set; }
        public string pswrd { get; set; }
    }
}
