//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class appointment_table
    {
        
        public int appointment_id { get; set; }
       

        public Nullable<int> hospitalid { get; set; }
        public Nullable<int> patientid { get; set; }
        public Nullable<int> doctorid { get; set; }
        public Nullable<System.DateTime> a_datetime { get; set; }
    
        public virtual doctors_table doctors_table { get; set; }
        public virtual hospital_TABLE hospital_TABLE { get; set; }
        public virtual patient_TABLE patient_TABLE { get; set; }
    }
}
