//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospital_TABLE()
        {
            this.appointment_table = new HashSet<appointment_table>();
            this.doctors_table = new HashSet<doctors_table>();
        }
    
        public int h_id { get; set; }
        public string h_name { get; set; }
        public string email_id { get; set; }
        public string pswrd { get; set; }
        public Nullable<int> mobile_no { get; set; }
        public string h_address { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> cityid { get; set; }
        public string doctor { get; set; }
        public string doctor_qualification { get; set; }
        public string doctor_speciality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment_table> appointment_table { get; set; }
        public virtual city_table city_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctors_table> doctors_table { get; set; }
        public virtual state_table state_table { get; set; }
    }
}
